In [14]:
# Requirement
#For the homework due on Monday, September 9, I would like each team 
#to fit a fully connected feedforward network with two hidden layers, 
#where each hidden layer has 1,024 nodes.

#If 9, fit the Street View House Numbers data using ReLU. (our # is 29)

#Once you have trained the network, please submit through our class 
#website the following information:  Your accuracy on the test data set, 
#the time it took to train your network, and the trained network (with 
#all the weights and intercepts for each node).   I shall provide a 
#google form on our class website where you can submit that information.

In [15]:
#answer

In [16]:
#load the data
# 5. Street View House Numbers (SVHN) Dataset
# http://ufldl.stanford.edu/housenumbers/
# import from SciPy

import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt


%matplotlib inline

train_data=sio.loadmat('train_32x32.mat')
test_data=sio.loadmat('test_32x32.mat')
extra_data=sio.loadmat('extra_32x32.mat')

x_train = train_data['X']
y_train = train_data['y']
x_test = test_data['X']
y_test = test_data['y']
x_extra = extra_data['X']
y_extra = extra_data['y']


print(x_train.shape)
print(x_extra.shape)
print(y_train.shape)
print(y_extra.shape)
# Use extra data as train data
x_train = np.concatenate([x_train, x_extra],axis=3)
y_train = np.concatenate([y_train, y_extra])
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(np.unique(y_test))



#x_train_partial=x_train[:,:,:,0:60439]
#x_train_1=x_train_partial.reshape((60439, 32*32*3))
x_train_1=x_train.reshape((604388, 32*32*3))
print(x_train_1.shape)


#x_test_partial=x_test[:,:,:,0:2603]
#x_test_1=x_test_partial.reshape((2603, 32*32*3))
x_test_1=x_test.reshape((26032, 32*32*3))
print(x_test_1.shape)

import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

# define Keras model
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.layers import Flatten

#x_train_1=x_train.reshape((604388, 32*32*3)
x_train_1=x_train_1.astype('float32') / 255
#x_test_1=x_test.reshape((26032, 32*32*3))
x_test_1=x_test_1.astype('float32') / 255
y_train_m1=y_train
y_train_m1[y_train_m1==10]=0
#y_train_m1_partial=y_train_m1[0:60439,:]
y_test_m1=y_test
y_test_m1[y_test_m1==10]=0
#y_test_m1_partial=y_test_m1[0:2603,:]
#y_train_fla=y_train_m1.flatten()
#y_train_fla=y_train_m1_partial
y_train_fla=y_train_m1
y_train_cat=to_categorical(y_train_fla)
y_test_fla=y_test_m1
#y_test_fla=y_test_m1_partial
#y_test_fla=y_test_m1.flatten()
y_test_cat=to_categorical(y_test_fla)

print(y_train_fla)
print(y_train_cat.shape)
print(np.unique(y_train_m1))



(32, 32, 3, 73257)
(32, 32, 3, 531131)
(73257, 1)
(531131, 1)
(32, 32, 3, 604388)
(604388, 1)
(32, 32, 3, 26032)
(26032, 1)
[ 1  2  3  4  5  6  7  8  9 10]
(604388, 3072)
(26032, 3072)
[[1]
 [9]
 [2]
 ...
 [2]
 [1]
 [4]]
(604388, 10)
[0 1 2 3 4 5 6 7 8 9]


In [17]:
model = Sequential()
model.add(Dense(1024, activation='relu',input_shape=(32 * 32 * 3,)))
model.add(Dense(1024, activation='relu'))
model.add(Dense(10, activation='softmax'))

# compile keras model
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# fit the keras model on the dataset
#model.fit(x_train_1, y_train_cat, batch_size=128, epochs=5)
model.fit(x_train_1, y_train_cat, batch_size=1024, epochs=5)
results = model.evaluate(x_test_1, y_test_cat)

#print(results)
#print(model.metrics_names)
test_loss, test_acc = model.evaluate(x_test_1, y_test_cat)
print('test_acc:', test_acc)
print('test_loss:', test_loss)

Epoch 1/5
604388/604388 [==============================] - 96s 158us/step - loss: 13.3123 - acc: 0.1725
Epoch 2/5
604388/604388 [==============================] - 91s 151us/step - loss: 13.3334 - acc: 0.1728
Epoch 3/5
604388/604388 [==============================] - 91s 151us/step - loss: 13.3334 - acc: 0.1728
Epoch 4/5
604388/604388 [==============================] - 93s 154us/step - loss: 13.3334 - acc: 0.1728
Epoch 5/5
26032/26032 [==============================] - 3s 105us/step
test_acc: 0.1958743085433313
test_loss: 12.960974645819778


In [18]:
#weights for 1st hidden layer
print('Weights for 1st hidden layer')
print(model.layers[0].get_weights()[0])
#intercept for 1st hidden layer
print("Intercept for 1st hidden layer")
print(model.layers[0].get_weights()[1])

#weights for 2nd hidden layer
print('Weights for 2nd hidden layer')
print(model.layers[1].get_weights()[0])
#intercept for 2nd hidden layer
print("Intercept for 1st hidden layer")
print(model.layers[1].get_weights()[1])

#weights for output layer
print('Weights for output layer')
print(model.layers[2].get_weights()[0])
#intercept for output layer
print("Intercept for output layer")
print(model.layers[2].get_weights()[1])

Weights for 1st hidden layer
[[-0.0093034   0.0360424   0.00770083 ...  0.00746725 -0.03045951
  -0.03569824]
 [ 0.0232445  -0.00432048 -0.01679118 ... -0.0307522  -0.0155011
   0.03703539]
 [ 0.02705462  0.02439425 -0.02966737 ... -0.00137646 -0.03737674
   0.03760207]
 ...
 [ 0.01737762 -0.02599672  0.0163582  ... -0.03237033 -0.03630818
   0.01674353]
 [-0.01006281  0.01566343  0.01307365 ... -0.0237109   0.01948151
   0.0241727 ]
 [ 0.04281557 -0.0147848   0.01624987 ... -0.01964259 -0.00591657
   0.00681869]]
Intercept for 1st hidden layer
[ 6.3034231e-03 -2.4948735e-05  0.0000000e+00 ... -3.1619882e-03
 -3.1612741e-03  1.7475104e-05]
Weights for 2nd hidden layer
[[ 0.0360515   0.05223205 -0.03081032 ... -0.03214793  0.03658938
  -0.01895358]
 [-0.00773264  0.0575212  -0.0353187  ... -0.03049078 -0.04400608
  -0.00129906]
 [ 0.04303432 -0.01972663 -0.00825481 ... -0.00224712 -0.00772082
  -0.01980191]
 ...
 [-0.03426374  0.03084737  0.04066868 ... -0.01347448 -0.0341806
  -0.00356