In [1]:
# Requirement
#For the homework due on Monday, September 9, I would like each team 
#to fit a fully connected feedforward network with two hidden layers, 
#where each hidden layer has 1,024 nodes.

#If 9, fit the Street View House Numbers data using ReLU. (our # is 29)

#Once you have trained the network, please submit through our class 
#website the following information:  Your accuracy on the test data set, 
#the time it took to train your network, and the trained network (with 
#all the weights and intercepts for each node).   I shall provide a 
#google form on our class website where you can submit that information.

In [2]:
#answer

In [3]:
#load the data
# 5. Street View House Numbers (SVHN) Dataset
# http://ufldl.stanford.edu/housenumbers/
# import from SciPy

import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt


%matplotlib inline

train_data=sio.loadmat('train_32x32.mat')
test_data=sio.loadmat('test_32x32.mat')
extra_data=sio.loadmat('extra_32x32.mat')

x_train = train_data['X']
y_train = train_data['y']
x_test = test_data['X']
y_test = test_data['y']
x_extra = extra_data['X']
y_extra = extra_data['y']


print(x_train.shape)
print(x_extra.shape)
print(y_train.shape)
print(y_extra.shape)
# Use extra data as train data
x_train = np.concatenate([x_train, x_extra],axis=3)
y_train = np.concatenate([y_train, y_extra])
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(np.unique(y_test))



#x_train_partial=x_train[:,:,:,0:60439]
#x_train_1=x_train_partial.reshape((60439, 32*32*3))
x_train_1=x_train.reshape((604388, 32*32*3))
print(x_train_1.shape)


#x_test_partial=x_test[:,:,:,0:2603]
#x_test_1=x_test_partial.reshape((2603, 32*32*3))
x_test_1=x_test.reshape((26032, 32*32*3))
print(x_test_1.shape)

import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

# define Keras model
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.layers import Flatten

#x_train_1=x_train.reshape((604388, 32*32*3)
x_train_1=x_train_1.astype('float32') / 255
#x_test_1=x_test.reshape((26032, 32*32*3))
x_test_1=x_test_1.astype('float32') / 255
y_train_m1=np.copy(y_train)
#y_test_m1=y_train
y_train_m1[y_train_m1==10]=0
#y_train_m1_partial=y_train_m1[0:60439,:]
y_test_m1=np.copy(y_test)
#y_test_m1=y_test
y_test_m1[y_test_m1==10]=0
#y_test_m1_partial=y_test_m1[0:2603,:]
#y_train_fla=y_train_m1.flatten()
#y_train_fla=y_train_m1_partial
y_train_fla=np.copy(y_train_m1)
#y_train_fla=y_train_m1
y_train_cat=to_categorical(y_train_fla)
#y_test_fla=y_test_m1
y_test_fla=np.copy(y_test_m1)
#y_test_fla=y_test_m1_partial
#y_test_fla=y_test_m1.flatten()
y_test_cat=to_categorical(y_test_fla)

print(y_train_fla)
print(y_train_cat.shape)
print(np.unique(y_train_m1))



(32, 32, 3, 73257)
(32, 32, 3, 531131)
(73257, 1)
(531131, 1)
(32, 32, 3, 604388)
(604388, 1)
(32, 32, 3, 26032)
(26032, 1)
[ 1  2  3  4  5  6  7  8  9 10]
(604388, 3072)
(26032, 3072)


Using TensorFlow backend.


[[1]
 [9]
 [2]
 ...
 [2]
 [1]
 [4]]
(604388, 10)
[0 1 2 3 4 5 6 7 8 9]


In [4]:
model = Sequential()
model.add(Dense(1024, activation='relu',input_shape=(32 * 32 * 3,)))
model.add(Dense(1024, activation='relu'))
model.add(Dense(10, activation='softmax'))

# compile keras model
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# fit the keras model on the dataset
#model.fit(x_train_1, y_train_cat, batch_size=128, epochs=5)
model.fit(x_train_1, y_train_cat, batch_size=1024, epochs=5)
results = model.evaluate(x_test_1, y_test_cat)

#print(results)
#print(model.metrics_names)
test_loss, test_acc = model.evaluate(x_test_1, y_test_cat)
print('test_acc:', test_acc)
print('test_loss:', test_loss)

W0908 14:51:54.928500 4487394752 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0908 14:51:54.944764 4487394752 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0908 14:51:54.976101 4487394752 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0908 14:51:55.063349 4487394752 deprecation_wrapper.py:119] From /anaconda3/lib/python3.7/site-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0908 14:51:55.089871 4487394752 deprecation_wrapper.py:119] From /anaconda3

Epoch 1/5
604388/604388 [==============================] - 98s 161us/step - loss: 13.3153 - acc: 0.1726
Epoch 2/5
604388/604388 [==============================] - 93s 154us/step - loss: 13.3334 - acc: 0.1728
Epoch 3/5
604388/604388 [==============================] - 96s 159us/step - loss: 13.3334 - acc: 0.1728
Epoch 4/5
604388/604388 [==============================] - 94s 155us/step - loss: 13.3334 - acc: 0.1728
Epoch 5/5
26032/26032 [==============================] - 3s 106us/step
test_acc: 0.1958743085433313
test_loss: 12.960974645819778


In [5]:
#weights for 1st hidden layer
print('Weights for 1st hidden layer')
print(model.layers[0].get_weights()[0])
#intercept for 1st hidden layer
print("Intercept for 1st hidden layer")
print(model.layers[0].get_weights()[1])

#weights for 2nd hidden layer
print('Weights for 2nd hidden layer')
print(model.layers[1].get_weights()[0])
#intercept for 2nd hidden layer
print("Intercept for 1st hidden layer")
print(model.layers[1].get_weights()[1])

#weights for output layer
print('Weights for output layer')
print(model.layers[2].get_weights()[0])
#intercept for output layer
print("Intercept for output layer")
print(model.layers[2].get_weights()[1])

Weights for 1st hidden layer
[[ 1.0522465e-02 -1.4043618e-02 -3.1204492e-02 ...  1.4050596e-02
   1.1647186e-02 -3.7377279e-02]
 [ 9.1072004e-03  1.2754792e-02 -9.7992150e-03 ... -2.7137410e-02
   9.3547627e-05 -3.3123523e-02]
 [ 1.5395223e-02  2.8454669e-02 -1.4765278e-02 ...  3.9770611e-02
  -8.0839433e-03  2.3467045e-02]
 ...
 [-5.3190701e-03  4.0327903e-02 -3.8459614e-02 ...  8.8878702e-03
  -2.8149525e-02 -1.2112396e-02]
 [ 3.3947017e-02 -1.6440306e-02 -2.1226667e-02 ... -1.7458769e-03
   2.1668760e-02  1.4322467e-02]
 [-4.4390708e-03 -2.4621667e-02  8.6124688e-03 ... -3.2901987e-02
  -8.0372747e-03 -1.0644995e-02]]
Intercept for 1st hidden layer
[-0.00316146  0.0031619  -0.00316219 ...  0.00316105 -0.00316214
  0.        ]
Weights for 2nd hidden layer
[[-0.05301954 -0.02937036  0.0135743  ... -0.03665827  0.00868513
   0.01186578]
 [ 0.01731173  0.05342041 -0.04946553 ... -0.01933712  0.00125752
  -0.00359508]
 [-0.02506833 -0.04257576  0.0493627  ...  0.04265726  0.04097372
   0